<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>About Angry Birds List</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/purecss@3.0.0/build/pure-min.css" integrity="sha384-X38yfunGUhNzHpBaEBsWLO+A0HDYOQi8ufWDkZ0k9e0eXz/tH3II7uKZ9msv++Ls" crossorigin="anonymous">
    <!--Using Pure CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <!-- Using Bootstrap for CSS simplicity -->
   </head>
   <body style="background-color: bisque; overflow: scroll;">
    <!--navigation bar-->
    <nav class="navbar" style="background-color: #288435; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;" data-bs-theme="light">
      <div class="container-fluid">
    <a class="navbar-brand" style="font-size: 40px;" aria-disabled="true">
         Angry Birds List
        <img src="/redBird.png" alt="Logo" width="30" height="24" class="d-inline-block align-text-bottom">
    </a>
        <li class="nav-item" style= "list-style-type:none; font-size: 28px;" >
          <a class="nav-link active" aria-current="page" href="index.html">Home</a>
        </li>
        <li class="nav-item" style= "list-style-type:none; font-size: 28px;">
          <a class="nav-link" href="about.html">About</a>
        </li>
        <li class="nav-item dropdown" style= "list-style-type:none; font-size: 28px;">
          <a class="nav-link" href="details.html">Details</a>
        </li>
        <li class="nav-item" style= "list-style-type:none; font-size: 28px;">
          <a class="nav-link" href="new-character-form.html">Add A Character</a>
        </li>     
     </div>  
    </nav>
    <br><br>
    <br><br> 
    <!--main content for this page-->
        <div class="container" style="padding-bottom: 140px">
            <table>
                <tr>
                    <th scope="col" style="padding-right: 30px; padding-left: 120px;"> <img src="/aboutImage.jpg"></th>
                    <th scope="col" style="padding-left: 90px;">
                        <div class="card text-center bg-transparent" style="border: unset; padding-bottom: 250px;">
                            <div class="card-header bg-transparent" style="height: 60px; font-size: 40px; font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: saddlebrown;">
                                <i>About this website</i>
                            </div>
                            <div class="card-body">
                                <p class="card-text">This website was made for my software engineering class. The objective was to make a website of a fictional universe of our choice, and so 
                                    I decided to do angry birds. This was one of my all-time favorite games to play growing up, so why not pay homage to it?
                                For theme, I decided to focus on simplicity and neatness, with the main colors being red, green, beige/brown, and black as these colors together remind me of the game. </p>
                            </div>
                            </div>
                    </th>
                </tr>
            </table>
                 <br><br>  
            <br><br>
        </div> 

     <!--footer--> 
       <footer style="background-color: rgba(255, 255, 255, 0.582); text-align: center; font-size: 12px;">Angry Birds List is for educational purposes. I do not own Angry Birds and all images belong to the rightful owners.</footer>
    </body>
</html>